FROM node:24.0.0-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --force --loglevel verbose

EXPOSE 3000

EXPOSE 9999

ENV PORT=3000

CMD ["sh", "-c", "npx prisma generate && npm run dev & npm run socket"]