volumes:
  node_modules:
  .next:

services:
  app-staging:
    build:
      context: ./
      dockerfile: ./Dockerfile
    profiles: ["staging"]
    ports:
      - 3000:3000
    env_file:
      - .env

  app-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    profiles: ["dev"]
    ports:
      - 3000:3000
    volumes:
      - "./:/app/:ro"
      - "node_modules:/app/node_modules"
      - ".next:/app/.next"
    env_file:
      - .env
    environment:
      - MONGODB_ADDRESS=${MONGODB_ADDRESS:-172.16.100.101}
      - MONGODB_PORT=${MONGODB_PORT:-27017}

  db-dev:
    image: mongo:8.0.9-noble
    profiles: ["dev"]
    restart: always
    logging:
        options:
            max-size: 1g
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      dev-network:
        ipv4_address: ${MONGODB_ADDRESS:-172.16.100.101}

networks:
  dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24